=== kamy333/ikamych/SetUp/library.dtd
<!ELEMENT library (book*)>
        <!ELEMENT book (title, author, genre, chapter*)>
        <!ATTLIST book isbn ID #REQUIRED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT chapter (chaptitle,text)>
        <!ATTLIST chapter position NMTOKEN #REQUIRED>
        <!ELEMENT chaptitle (#PCDATA)>
        <!ELEMENT text (#PCDATA)>

=== kamy333/ikamych/SetUp/library.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <book isbn="isbn1234">
        <title>A Book</title>
        <author>An Author</author>
        <genre>Horror</genre>
        <chapter position="first">
            <chaptitle>chapter one</chaptitle>
            <text><![CDATA[Lorem Ipsum...]]></text>
        </chapter>
    </book>
    <book isbn="isbn1235">
        <title>Another Book</title>
        <author>Another Author</author>
        <genre>Science Fiction</genre>
        <chapter position="first">
            <chaptitle>chapter one</chaptitle>
            <text><![CDATA[<i>Sit Dolor Amet...</i>]]></text>
        </chapter>
    </book>
</library>
